---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: spring-boot-example
  name: spring-boot-example-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: spring-boot-example
    spec:
      containers:
      - image: chandar19/spring-boot-example
        name: spring-boot-example
        ports:
        - name: spring-boot-example
          containerPort: 8080  
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: spring-boot-example
  name: spring-boot-example
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: spring-boot-example
